### ISSUE TITLE
is it still good to use the current version of clojure

### ISSUE THREAD

**Issue by oskarz1234** [schani/clojurec#36]

**Comment by schani** [comment]
I haven't touched ClojureC in a long time.  I would be surprised if it works on the latest Clojure, but please let me know if you try it out.

**Comment by oskarz1234** [comment]
Im on arch linux  what sould be the output of this
 **pkg-config --cflags bdw-gc**

**Comment by schani** [comment]
I really don't know.

Have you tried building ClojureC?  Does it fail?  If it does, what's the output?

**Comment by oskarz1234** [comment]
do you mean **lein test**?

**Comment by nakkaya** [comment]
@oskarz1234 If you are looking for a Clojure to C++ compiler you can check out Ferret. [1]

[1] https://github.com/nakkaya/ferret
